# Generated by Django 6.0.4 on 2026-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vocabulary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headword", models.CharField(max_length=255)),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("noun", "Noun"),
                            ("verb", "Verb"),
                            ("adjective", "Adjective"),
                            ("adverb", "Adverb"),
                            ("preposition", "Preposition"),
                            ("pronoun", "Pronoun"),
                            ("conjunction", "Conjunction"),
                            ("determiner", "Determiner"),
                            ("interjection", "Interjection"),
                            ("number", "Number"),
                        ],
                        max_length=55,
                    ),
                ),
                (
                    "cefr",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
            options={
                "db_table": "vocabulary",
            },
        ),
    ]
